using PeakTrailRecorder;
using System.Net;
using System.Net.Sockets;
using System.Text;

static void Assert(bool condition, string message, string actual = "")
{
    if (!condition) throw new InvalidOperationException($"{message} (actual: '{actual}')");
}

// Vectors generated by the server's reference implementation
// (PeakTrailPlatform/server/run-code.mjs). Any change here breaks relay merging.
const string runId = "9bf6aaa3-0712-49e2-83d0-6e54930c3d90";
Assert(RunCode.Derive(runId, 0) == "erek", "attempt 0 must match the JS reference", RunCode.Derive(runId, 0));
Assert(RunCode.Derive(runId, 1) == "nkz4", "attempt 1 must match the JS reference");
Assert(RunCode.Derive(runId, 2) == "hhxc", "attempt 2 must match the JS reference");
Assert(RunCode.Derive(runId, 3) == "r98f", "attempt 3 must match the JS reference");
Assert(RunCode.Derive("00000000-0000-0000-0000-000000000000", 0) == "a4vd", "empty-guid vector must match");
Assert(RunCode.Derive("not-a-guid", 0) == "96a7", "non-guid vector must match");

// Normalization: uppercase and braced GUID forms derive the same code, so every
// teammate lands on one run regardless of how their client formats the id.
Assert(RunCode.Derive("9BF6AAA3-0712-49E2-83D0-6E54930C3D90") == "erek", "uppercase GUID normalizes");
Assert(RunCode.Derive("{9bf6aaa3-0712-49e2-83d0-6e54930c3d90}") == "erek", "braced GUID normalizes");
Assert(RunCode.Derive("9bf6aaa3071249e283d06e54930c3d90") == "erek", "compact hex normalizes to the same code");

// The relay confirms codes by re-derivation; collisions walk the attempt sequence.
Assert(RunCode.Matches(runId, "erek"), "the derived code is confirmed");
Assert(RunCode.Matches(runId, "nkz4"), "fallback attempts are confirmed too");
Assert(!RunCode.Matches(runId, "zzzz"), "an arbitrary code is not confirmed");
Assert(!RunCode.Matches(null, "erek"), "a missing runId confirms nothing");
Assert(!RunCode.Matches(runId, null), "a missing code confirms nothing");

// Format: 4 characters from the unambiguous alphabet only.
string code = RunCode.Derive(runId);
Assert(code.Length == RunCode.Length, "codes are exactly 4 characters");
foreach (char character in code)
{
    Assert(RunCode.Alphabet.Contains(character), "codes use only the unambiguous alphabet");
}

Assert(LiveRelayConnection.DefaultServerUrl == "https://peak.mylus.cn", "recorder defaults to the deployed HTTPS relay");
var relay = new LiveRelayConnection(" https://peak.mylus.cn/ ");
Assert(relay.ServerUrl == LiveRelayConnection.DefaultServerUrl, "relay URL normalizes trailing slash and whitespace");
using (var client = relay.CreateHttpClient(TimeSpan.FromSeconds(2)))
{
    Assert(client.DefaultRequestHeaders.Authorization == null, "direct public publishing does not require credentials");
}

// A relay response must not redirect telemetry to a different endpoint.
using (var listener = new TcpListener(IPAddress.Loopback, 0))
using (var deadline = new CancellationTokenSource(TimeSpan.FromSeconds(5)))
{
    listener.Start();
    int port = ((IPEndPoint)listener.LocalEndpoint).Port;
    string relayUrl = $"http://127.0.0.1:{port}";
    var reply = Task.Run(async () =>
    {
        using TcpClient socket = await listener.AcceptTcpClientAsync(deadline.Token);
        await using NetworkStream stream = socket.GetStream();
        using var reader = new StreamReader(stream, Encoding.ASCII, leaveOpen: true);
        var headers = new List<string>();
        while (await reader.ReadLineAsync(deadline.Token) is { Length: > 0 } line) headers.Add(line);
        Assert(!headers.Any(line => line.StartsWith("Authorization:", StringComparison.OrdinalIgnoreCase)), "transport sends no authentication header");
        byte[] response = Encoding.ASCII.GetBytes($"HTTP/1.1 302 Found\r\nLocation: {relayUrl}/redirected\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");
        await stream.WriteAsync(response, deadline.Token);
    }, deadline.Token);
    using var client = new LiveRelayConnection(relayUrl).CreateHttpClient(TimeSpan.FromSeconds(3));
    using var response = await client.GetAsync(relayUrl + "/api/runs", deadline.Token);
    await reply;
    Assert(response.StatusCode == HttpStatusCode.Found, "relay redirects are returned, never followed");
}

Console.WriteLine("PeakTrail live contract passed.");
