using PeakTrailRecorder;

static void Assert(bool condition, string message, string actual = "")
{
    if (!condition) throw new InvalidOperationException($"{message} (actual: '{actual}')");
}

// Vectors generated by the server's reference implementation
// (PeakTrailPlatform/server/run-code.mjs). Any change here breaks relay merging.
const string runId = "9bf6aaa3-0712-49e2-83d0-6e54930c3d90";
Assert(RunCode.Derive(runId, 0) == "erek", "attempt 0 must match the JS reference", RunCode.Derive(runId, 0));
Assert(RunCode.Derive(runId, 1) == "nkz4", "attempt 1 must match the JS reference");
Assert(RunCode.Derive(runId, 2) == "hhxc", "attempt 2 must match the JS reference");
Assert(RunCode.Derive(runId, 3) == "r98f", "attempt 3 must match the JS reference");
Assert(RunCode.Derive("00000000-0000-0000-0000-000000000000", 0) == "a4vd", "empty-guid vector must match");
Assert(RunCode.Derive("not-a-guid", 0) == "96a7", "non-guid vector must match");

// Normalization: uppercase and braced GUID forms derive the same code, so every
// teammate lands on one run regardless of how their client formats the id.
Assert(RunCode.Derive("9BF6AAA3-0712-49E2-83D0-6E54930C3D90") == "erek", "uppercase GUID normalizes");
Assert(RunCode.Derive("{9bf6aaa3-0712-49e2-83d0-6e54930c3d90}") == "erek", "braced GUID normalizes");
Assert(RunCode.Derive("9bf6aaa3071249e283d06e54930c3d90") == "erek", "compact hex normalizes to the same code");

// The relay confirms codes by re-derivation; collisions walk the attempt sequence.
Assert(RunCode.Matches(runId, "erek"), "the derived code is confirmed");
Assert(RunCode.Matches(runId, "nkz4"), "fallback attempts are confirmed too");
Assert(!RunCode.Matches(runId, "zzzz"), "an arbitrary code is not confirmed");
Assert(!RunCode.Matches(null, "erek"), "a missing runId confirms nothing");
Assert(!RunCode.Matches(runId, null), "a missing code confirms nothing");

// Format: 4 characters from the unambiguous alphabet only.
string code = RunCode.Derive(runId);
Assert(code.Length == RunCode.Length, "codes are exactly 4 characters");
foreach (char character in code)
{
    Assert(RunCode.Alphabet.Contains(character), "codes use only the unambiguous alphabet");
}

Console.WriteLine("PeakTrail live contract passed.");
