import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { siteReleaseOptions, validateSiteRelease } from "../../tools/lib/site-release.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const htmlPath = resolve(root, "index.html");
const html = readFileSync(htmlPath, "utf8");
const missing = [];
const { product } = siteReleaseOptions(process.argv.slice(2));
const downloadRelease = validateSiteRelease(JSON.parse(readFileSync(resolve(root, `../data/${product}/release.json`), "utf8")), product);

for (const entrypoint of [html, ...["guide.html", "routes.html"].filter(path => existsSync(resolve(root, path))).map(path => readFileSync(resolve(root, path), "utf8"))]) for (const match of entrypoint.matchAll(/(?:src|href)="([^"#]+)"/g)) {
  const reference = match[1];
  if (/^(?:data:|https?:|\/\/)/i.test(reference)) continue;
  // This one pinned release is generated by stage-site, not kept in web/ or Git.
  if (reference.replace(/^\.\//, "") === downloadRelease.downloadPath) continue;
  const target = resolve(root, reference.replace(/^\.\//, ""));
  if (!existsSync(target)) missing.push(reference);
}

const importMapMatch = html.match(/<script type="importmap">([\s\S]*?)<\/script>/);
if (!importMapMatch) throw new Error("index.html 缺少 Three.js import map");
JSON.parse(importMapMatch[1]);

for (const source of ["src/app.js", "src/protocol.js", "src/scene.js", "src/community-map-panel.js", "src/community-routes.js"]) {
  const contents = readFileSync(resolve(root, source), "utf8");
  if (contents.includes("innerHTML")) throw new Error(`${source} 不应使用 innerHTML`);
}

if (missing.length) throw new Error(`缺少本地静态资源：${missing.join(", ")}`);
console.log("Static entrypoint, import map and local asset references are valid.");
