<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>

    <PathBeforeSteam Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(MSBuildProgramFiles32)/</PathBeforeSteam>
    <PathBeforeSteam Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.local/share/</PathBeforeSteam>
    <PEAKGameRootDir Condition="'$(PEAKGameRootDir)' == ''">$(PathBeforeSteam)Steam/steamapps/common/PEAK/</PEAKGameRootDir>
    <ManagedDir>$(PEAKGameRootDir)PEAK_Data/Managed/</ManagedDir>
    <BepInExCoreDir>$(PEAKGameRootDir)BepInEx/core/</BepInExCoreDir>
  </PropertyGroup>
</Project>
